name: VMAlias
version: 2.0.2
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: VMPE Development Team
description: Allows users to view all the usernames one user has used
main: Alias\MainClass

commands:
  alias:
    description: "Allows users to view all the usernames one user has used"
    usage: "/alias <username>"
    permission: "alias.alias"
  setalias:
    description: "Change Alias's settings"
    usage: "/setalias <cid/ip>"
    permission: "alias.setalias"
  aliasip:
    description: "Uses IP"
    usage: "/aliasip <username>"
    permission: "alias.aliasip"
  aliascid:
    description: "Uses Client ID"
    usage: "/aliascid <username>"
    permission: "alias.aliascid"
  checkalias:
    description: "Check what Alias is set to"
    usage: "/checkalias"
    permission: "alias.checkalias"

permissions:
    alias:
        default: op
        description: "Alias commands"
        children:
            alias.alias:
                default: op
                description: "Allows users to view all the usernames one user has used"
            alias.setalias:
                default: op
                description: "Change settings for Alias"
            alias.aliasip:
                default: op
                description: "Uses IP"
            alias.aliascid:
                default: op
                description: "Uses Client ID"
            alias.checkalias:
                default: op
                description: "Checks what Alias is set to"
